server:
  port: 7700
  tomcat.uri-encoding: utf-8

spring:
  application:
    name: service-tm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.157.251:3306/seata_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Teamer2018.
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 114.116.14.26:8848
        namespace: 8f11aeb1-5042-461b-b88b-d47a7f7e01c0

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: seata-demo
  service:
    vgroup-mapping:
      seata-demo: guangzhou
  config:
    type: file
    file:
      name: file.conf
  registry:
    type: nacos
    nacos:
      cluster: default
      group: DEFAULT_GROUP
      application: seata-server
      server-addr: 114.116.14.26:8848
      namespace: 8f11aeb1-5042-461b-b88b-d47a7f7e01c0